CONFIG_UART        := y
CONFIG_XML         := y

CONFIG_CRYPTO      := y
CONFIG_CRYPTO_TZCC := y
CONFIG_CRYPTO_KDF  := y
CONFIG_CRYPTO_SEJ  := y
CONFIG_CRYPTO_SSR  := y

CONFIG_MMC         := y
CONFIG_RPMB        := y
CONFIG_MMC_RPMB    := y
